/** Every icon symbol id defined once in `icon-sprite.component.html` (as
 * `#icon-{name}`) and referenced from `IconComponent` via `<use>`. */
export type IconName =
  | 'pin'
  | 'phone'
  | 'whatsapp'
  | 'mail'
  | 'linkedin'
  | 'github'
  | 'download'
  | 'grid'
  | 'search'
  | 'close'
  | 'sun'
  | 'moon'
  | 'up'
  | 'menu'
  | 'external'
  | 'arrow'
  | 'code'
  | 'layers'
  | 'route'
  | 'wave'
  | 'mirror'
  | 'gauge'
  | 'shield'
  | 'seo'
  | 'cap'
  | 'doc'
  | 'globe'
  | 'copy';
